sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: P7FQGlSAlOzOx2mjF3M09DMWlLVmxEKYExTlARXufoH9vS+CrdxYeVqCcXGbzOoy/YfO0MpXhLWba6wimLsNg97bHOIO2Nid30gMeCfbW0IYJTuZriFbzf4xTEtRC6cepkZrJCoIuoYMqg9+eKvQYaeeqlTTnZgC6mpYWMqAseYLH9/udQsLaSLIThFbvApRqKtmY0q8I9P2MoElmnNwMEAzQIt6GhfGvVXFWcyDBElLw92xwbnMLuD1Exd4JkZO2U6kgnl6ZjK5EEpem6OOYhKxD2u+1rkFbCto6ttTK8z8dnSJhCs2jIG5hxlCD++wZwQ7XzENUIhmadTm5ruLs5WEiOvTENm+c2wp2CwvNQanueLibkb25niMmU2PiArEQsrnLbllk2/mwDeGBGgUeahkHyvgr9haUJCUmylE2uzL61jkWXPvI5zzm72MHIjTMUhODaC0GWGj6gx1nPprnIUl1zp32RAQ1NPM4yicSo6BOZEcXFLcYsyMRZvSG8okeEKkAVmXQI5DX8m3eZWsoQtLbK7hSsRzBUCdo00tEErXeWRutw1r6jetLJc8jU+Z9Z5DmjR1fAzZ/I8+ifY/EZzNufObkqX1g19Jp6XNt8pSqN/QMMQ6Y7YR0mXNoRBnRR9RKcdKCxyV+9pvZ9uzxJQZy7KGeR7/fi1cICcdI6Q=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Lone-Star-Ranger--A-Romance-of-the-Border_1027
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy